### ISSUE TITLE
Imageoptim not working with Middleman 4.0.0.alpha

### ISSUE THREAD

**Issue by KamilLelonek** [plasticine/middleman-imageoptim#35]
```
/Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim/manifest_resource.rb:3:in `<module:Imageoptim>': uninitialized constant Middleman::Sitemap::Resource (NameError)
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim/manifest_resource.rb:2:in `<module:Middleman>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim/manifest_resource.rb:1:in `<top (required)>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim.rb:7:in `require'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-imageoptim-0.2.0/lib/middleman-imageoptim.rb:7:in `<top (required)>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `require'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `each'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:72:in `block in require'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `each'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler/runtime.rb:61:in `require'
  from /Users/user_name/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.7.10/lib/bundler.rb:134:in `require'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/load_paths.rb:33:in `setup_bundler'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-core-4.0.0.alpha.6/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/gems/middleman-cli-4.0.0.alpha.6/bin/middleman:10:in `<top (required)>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/middleman:23:in `load'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/middleman:23:in `<main>'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
  from /Users/user_name/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by alem0lars** [comment]
Same problem here

**Comment by plasticine** [comment]
Yep—[this is expected](https://travis-ci.org/plasticine/middleman-imageoptim).

I’ve not had time to look into support for Middleman 4.0, and until it is released I would not expect it to work. PRs very welcome though.
