### ISSUE TITLE
ENOENT error on Build

### ISSUE THREAD

**Issue by dwhoban** [plasticine/middleman-imageoptim#44]
Have received the following error, have tested with both assest hash on and off.

```
PS C:\Users\HobanD\sites\pt.dev> bundle exec middleman build
   identical  build/assets/css/all-685c52cb.css
   identical  build/assets/img/middleman-50d9de35.png
   identical  build/assets/img/background-29e26e74.png
   identical  build/assets/js/all-da39a3ee.js
   identical  build/index.html
      create  build/imageoptim.manifest.yml
      remove  build/sitemap.xml
      remove  build/sitemap.xml.gz
      create  build/sitemap.xml
      create  build/sitemap.xml.gz
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim_pack-0.2.1.20150702/lib/image_optim/pack.rb:67:in ``': No such file or directory - uname -s (Errno::ENOENT)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim_pack-0.2.1.20150702/lib/image_optim/pack.rb:67:in `<module:Pack>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim_pack-0.2.1.20150702/lib/image_optim/pack.rb:7:in `<class:ImageOptim>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim_pack-0.2.1.20150702/lib/image_optim/pack.rb:4:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim-0.20.2/lib/image_optim/config.rb:129:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim-0.20.2/lib/image_optim/config.rb:129:in `pack'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim-0.20.2/lib/image_optim.rb:71:in `block in initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim-0.20.2/lib/image_optim.rb:70:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/image_optim-0.20.2/lib/image_optim.rb:70:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:83:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:83:in `optimizer'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:58:in `block in optimizable_images'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:57:in `select'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:57:in `optimizable_images'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:53:in `updated_images'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:23:in `process_images'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/optimizer.rb:12:in `optimize!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-imageoptim-0.2.1/lib/middleman-imageoptim/extension.rb:8:in `after_build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/extension.rb:159:in `blockin bind_after_build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `proc!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/uber-0.0.13/lib/uber/options.rb:69:in `evaluate_for'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/cli/build.rb:72:in `build'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:72:in `method_missing'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/cli.rb:20:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.12/bin/middleman:18:in `<top (required)>'
        from C:/Ruby22-x64/bin/middleman:23:in `load'
        from C:/Ruby22-x64/bin/middleman:23:in `<main>'
```

**Comment by Arcovion** [comment]
`image_optim` is not compatible with Windows.
